"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let addition = 4 + 4;
let subtraction = 10 - 2;
let multiplication = 2 * 4;
let division = 32 / 4;
console.log(addition);
console.log(subtraction);
console.log(multiplication);
console.log(division);
